[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
headers = {
  "Access-Control-Allow-Origin" = "*"
  "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
  "Access-Control-Allow-Headers" = "Content-Type"
}